### ISSUE TITLE
return the original register in apply!

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoPastaQ.jl#5]
We wil need an inplace version of `runcircuit`, or there actually are such function somewhere? @mtfishman 

https://github.com/QuantumBFS/YaoPastaQ.jl/blob/71de5f1acefc1c6f977376f96760a7050f9adf0a/src/YaoPastaQ.jl#L73

**Comment by mtfishman** [comment]
It is not yet implemented, but it would be implemented with a trivial definition in terms of `runcircuit` like:
```julia
function runcircuit!(psi, gates)
  gpsi = runcircuit(psi, gates)
  psi .= gpsi
  set_ortho_lims!(psi, ortho_lims(gpsi))
  return psi
end
```
since there isn't really an advantage to doing in-place circuit evolution with MPS (the dimensions of the tensors are always changing at every step, so you can't really reuse the memory).

**Comment by Roger-luo** [comment]
Yeah make sense, I think in this case, we should just replace the state field inside that register instead of doing `psi .= gpsi` which is a bit extra. @VarLad can you change the register struct to `mutable`? then replace the `state` field instead creating a new regsiter?

**Comment by VarLad** [comment]
@Roger-luo Not sure if I get what you mean. Replace state with what？

**Comment by Roger-luo** [comment]
@VarLad https://github.com/QuantumBFS/YaoPastaQ.jl/commit/2bf82bd21e7a817b654213753bc77640463fe64e

**Comment by VarLad** [comment]
I was just about to open a PR and ask if that was what you meant 🤣
That was fast of you @Roger-luo
